{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ template "prometheus-pushgateway.namespace" . }}
{{- with .Values.serviceMonitor.additionalLabels }}
  labels:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "prom-aggregation-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: api-port
{{- end }}
